repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 3.9.2
  #   hooks:
  #     - id: flake8
  #       language_version: python3
  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        args:
          - "--profile"
          - "black"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      # - id: check-yaml
#  - repo: https://github.com/feluelle/airflint
#    rev: v0.3.2-alpha
#    hooks:
#      - id: airflint
#        args: ["-a"]  # Use -a to apply the suggestions
#        additional_dependencies:  # Add all package dependencies you have in your dags, preferable with version spec
#          - apache-airflow
#          - apache-airflow-providers-amazon==6.0.0
  - repo: https://github.com/pycqa/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: ["--remove-all-unused-imports", "--in-place"]
