---
    name: Python style check
    on: [push]

    # When this workflow is queued, automatically cancel any previous running
    # or pending jobs from the same branch
    concurrency:
      group: style-${{ github.head_ref }}
      cancel-in-progress: true

    jobs:
      pre-commit:
        name: Run pre-commit hooks
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-python@v4
            with:
              python-version: '3.9'
              cache: 'pip' # caching pip dependencies
          - uses: pre-commit/action@v3.0.0
